--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/David-pm-pl/GhostPlayer
build-by-default: true
branches:
- main
projects:
  GhostPlayer:
    path: ""
    icon: icon.png
    libs:
    - src: muqsit/fakeplayer/FakePlayer
      version: ^0.1.4
    lint:
      phpstan: false
...
