--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/David-pm-pl/GhostPlayer
build-by-default: true
branches:
- main
projects:
  GhostPlayer:
    path: ""
    icon: icon.png
#    lint:
#      phpstan: false
...
