name: GhostPlayer
version: 0.0.2
api: 4.0.0
main: davidglitch04\GhostPlayer\Loader
src-namespace-prefix: davidglitch04\GhostPlayer
author: DavidGlitch04
website: https://github.com/DavidGlitch04
depend:
  - FakePlayer

permissions:
  ghostplayer.command.allow:
    default: op
    description: "Allow player to use ghostplayer command"
